#include "helper.h"
#include "visualLB.h"
#include "LBDefinitions.h"
#include "computeCellValues.h"

void writeVtkOutput(const double * const collideField, const flag_data * const flagField, const char * filename, unsigned int t, int xlength, int ylength, int zlength) {
  int i,j,k;
  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", filename, t );
  fp = fopen( szFileName, "w");

  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  // allocate space to store densities so we don't recompute them 
  // when computing the velocity
  double *densities = (double*) malloc(sizeof(double) * pow(xlength+2, 3));

  write_vtkHeader( fp, xlength);
  write_vtkPointCoordinates(fp, xlength, 1, 1, 1);

  // output density values for every inner cell
  fprintf(fp,"\n");
  fprintf(fp,"POINT_DATA %i \n", (xlength)*(xlength)*(xlength) );
  fprintf(fp, "SCALARS density float 1 \n"); 
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(i = 1; i < xlength+1; i++) {
    for(j = 1; j < xlength+1; j++) {
      for(k = 1; k < xlength+1; k++) {
        computeDensity(&collideField[INDEXOF(xlength, i,j,k,0)], &densities[FINDEXOF(xlength, i,j,k)]);
        fprintf(fp, "%f\n", densities[FINDEXOF(xlength, i,j,k)] );
      }
    }
  }

  // output flag values for every inner cell
  fprintf(fp, "\n");
  fprintf(fp, "SCALARS flag float 1 \n"); 
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(i = 1; i < xlength+1; i++) {
    for(j = 1; j < xlength+1; j++) {
      for(k = 1; k < xlength+1; k++) {
        fprintf(fp, "%f\n", (double)flagField[FINDEXOF(xlength, i,j,k)].flag);
      }
    }
  }

  // output velocity values for every inner cell
  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(i = 1; i < xlength+1; i++) {
    for(j = 1; j < xlength+1; j++) {
      for(k = 1; k < xlength+1; k++) {
        double velocity[3];
        computeVelocity(&collideField[INDEXOF(xlength, i,j,k,0)], densities+FINDEXOF(xlength, i, j, k), velocity);
        fprintf(fp, "%f %f %f\n", velocity[0], velocity[1], velocity[2]);
      }
    }
  }

  // cleanup
  free(densities);

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}

void write_vtkHeader( FILE *fp, int xlength)
{

  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel) \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");	
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i %i\n", xlength, xlength, xlength);
  fprintf(fp,"POINTS %i float\n", (xlength)*(xlength)*(xlength) );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int xlength, double dx, double dy, double dz)
{
  double originX = 0.0;
  double originY = 0.0;
  double originZ = 0.0;

  int i = 0;
  int j = 0;
  int k = 0;

  // generate equal-spaced grid points
  for(i = 0; i < xlength; i++) {
    for(j = 0; j < xlength; j++) {
      for (k = 0; k < xlength; k++) {
        fprintf(fp, "%f %f %f\n", originX+(i*dx), originY+(j*dy), originZ+(k*dz) );
      }
    }
  }
}

